In [2]:
"""
ESG Risk:

A Real-Time ESG Risk Scoring Framework for Company Filings 

Authored in 2025 by Aaron Walker


Change log:
- 04/09/2025: added def text_to_scored_ESG_() & def ESG_risk_score()

"""
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pdfplumber
import re
import urllib.request
from pdf_parser import url_to_pdf
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline # for using the models
import fitz  # PyMuPDF
import nltk

#Use ESG-BERT (Bidirectional Encoder Representations from Transformers) for natural language processing of company SEC filings
#Input: databbase of SEC filings by company.
#Outout: ESG Risk score and classifcation (Low, Med, High)

#To Do list:
# 1) ETL (Extract) pipeline using either responsibility reports.com (volentary ESG reports, likely effected by greenwashing) or SEC filings (best)
# 2) Transform & load: PDF sentence classification into E,S,G
# 3) Import ESG Models, return esg classifications per sentence
# 4) Import ESG sentence classifications, analyse and return sentiment
# 5) Calculate risk score and classify company
# 6+) Apply MLOPS and productionarise: Containerise, orchestrate, monitor -> finetune ESG hugging face model -> Visualisations in streamlit server
# Write up paper and compare with ESG literature

c:\Users\AS9Wa\.conda\envs\Main_Env\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
# 1) Extract pdfs given url to report

#Extract from:
#https://www.responsibilityreports.com/ and

#https://www.sec.gov/edgar/search/
#https://www.sec.gov/Archives/edgar/data/2488/000000248825000012/ex19_1amdstocktradingpolic.htm

company_url_list = [
"https://www.responsibilityreports.com/HostedData/ResponsibilityReports/PDF/NASDAQ_AMD_2024.pdf",
"https://www.responsibilityreports.com/HostedData/ResponsibilityReports/PDF/NYSE_MCD_2023.pdf",
"https://www.responsibilityreports.com/HostedData/ResponsibilityReports/PDF/LSE_BT_2023.pdf",
"https://www.responsibilityreports.com/HostedData/ResponsibilityReports/PDF/LSE_VTC_2023.pdf",
"https://www.responsibilityreports.com/HostedData/ResponsibilityReports/PDF/LSE_BARC_2024.pdf",
"https://www.responsibilityreports.com/HostedData/ResponsibilityReports/PDF/NYSE_BSAC_2024.pdf",
"https://www.responsibilityreports.com/HostedData/ResponsibilityReports/PDF/NASDAQ_AAPL_2024.pdf",
"https://www.responsibilityreports.com/HostedData/ResponsibilityReports/PDF/NYSE_HSBC_2024.pdf",
"https://www.responsibilityreports.com/HostedData/ResponsibilityReports/PDF/OTC_SSDIY_2024.pdf",
"https://www.responsibilityreports.com/HostedData/ResponsibilityReports/PDF/OTC_BAMGF_2024.pdf",
"https://www.responsibilityreports.com/HostedData/ResponsibilityReports/PDF/OTC_MBGAF_2024.pdf"
]

url_to_pdf(company_url_list)

In [14]:
pdf_path = r'data/LSE_BT_2023.pdf'

doc = fitz.open(pdf_path)

all_sentences = []

for page in doc:
    # Extract text blocks with positions
    blocks = page.get_text("blocks")
    # Sort top-to-bottom, then left-to-right
    blocks = sorted(blocks, key=lambda b: (round(b[1], 1), b[0]))

    page_text = " ".join(b[4] for b in blocks)  # merge block text
    sentences = nltk.sent_tokenize(page_text)
    all_sentences.extend(sentences)

print(all_sentences[:10])

['ESG\nAddendum \n2024\n to the BT Group plc \nAnnual Report 2024', 'Being transparent \nand accountable\nDisclosing policies and \nperformance\nIdentifying our ESG \npriorities\nBT Group Manifesto – \ntargets and progress \nFY23\n Being transparent \nand accountable\n Disclosing policies and \nperformance\nIdentifying our ESG \npriorities\nBT Group Manifesto – \ntargets and progress \nFY23\n Our social and \neconomic contribution\nEnvironmental \nmanagement\nEnvironmental data\nPeople data\nSustainability \nAccounting Standards \nBoard (SASB) index\n Our social and \neconomic contribution\nEnvironmental \nmanagement\nEnvironmental data\nPeople data\nSustainability \nAccounting Standards \nBoard (SASB) index\n Contents\n “As a responsible business, we \nopenly and regularly share the \nprogress we are making on\xa0the \nBT\xa0Group Manifesto and in \nsupport of\xa0our purpose, to \nconnect for good.', 'Disclosing policies and performance\n03\n Being transparent through our ESG \ndisclosures is essential in building trust \nwith all of our stakeholders.', 'It provides \ntangible proof of how we’re making a \npositive contribution to society and \nthe environment, and helps us to grow \nour business, reduce risk, and attract \nand retain diverse talent.', 'External recognition\n Identifying our ESG priorities\n04\n BT Group Manifesto key targets and \nprogress FY24\n06\n ESG ratings/rankings:\n CDP: We’re A Listed for climate for the eighth year \nrunning (top 2% of over 21,000 global reporters)\n Our social and economic \ncontribution\n08\n Clean200: we’re ranked in the top 200 public \ncompanies worldwide that earn the most revenue \nfrom clean, sustainable sources, supporting the \ntransition to a clean energy future\n Environmental management\n09\n We report on material ESG topics in our \nAnnual Report; this Addendum offers \nmore detailed data and disclosures to \nmeet growing expectations for \nenhanced transparency on ESG topics.', 'Oversight of progress on the Manifesto \nand our ESG reporting is integrated \nacross our governance structures.', 'Environmental data\n11\n EcoVadis: Advanced rating score of 73/100 \n(top\xa04% of over 600 companies assessed in the \ntelecoms sector)\n People data\n13\n - Colleague profile\n13\n Financial Times: Confirmed listing as one of \nEurope’s Climate Leaders 2023\n - Pay gap – supplementary data\n16\n FTSE4Good: Confirmed member of the Russell \nFTSE4Good index\n - \x07Inclusion, equity and diversity \ninitiatives – supplementary\n18\n ISS-ESG: Prime rating for ESG\n MSCI: AA rating for ESG investment risk \nand\xa0opportunities\n Sustainability Accounting \nStandards Board (SASB) index\n19\n Over recent years, we’ve seen a huge \nshift in the ESG reporting landscape, \nwhich advance the range of disclosures \nthat we and other businesses make.', 'We’d like to see greater levels of \nconsistency and further coordination \namong regulators and standard-\nsetters, to enable us to provide the \nmost meaningful, comparable and \nefficient response.', 'Sustainalytics: Low risk score of 19.7 for ESG \n(top\xa0quartile)\n Tortoise Responsibility100: Leading telecoms \ncompany and 6th overall in the 2023 UK FTSE100 \nratings across a range of ESG indicators (ranked \n1st on Climate)\n Vigeo Eiris (Moody’s): Advanced ESG rating \nscore of 60/100\n Awards:\n –\t Bosch Global Supplier Award for Sustainability, \nrecognising BT Group’s sustainability and Net \nZero contribution from among 35,000 suppliers \n –\t Franco-British Trade & Investment Awards – BT \nGroup were the Sustainability category winners\n –\t Prime Minister’s Award for Cyber awarded to \nBT\xa0Group, for helping customers avoid text \nmessage scams\n Simon Lowth\nChief Financial Officer\n –\t Payroll Giving Silver Award quality mark from \nHM Government awarded to BT Group, for \ngenerating sustainable income sources for \nUK\xa0charities through Payroll Giving.', '02\nBT Group plc ESG Addendum to the BT Group plc Annual Report 2024\n02\nBT Group plc ESG Addendum to the BT Group plc Annual Report 2024']

In [15]:
def extract_sentences(pdf_path):
    doc = fitz.open(pdf_path)
    all_sentences = []

    for page in doc:
        #get text coordinates
        blocks = page.get_text("blocks")
        page_width = page.rect.width

        #left and right columns
        left_col = [b for b in blocks if b[0] < page_width/2]
        right_col = [b for b in blocks if b[0] >= page_width/2]

        #sort within each column by y (top to bottom)
        left_col = sorted(left_col, key=lambda b: b[1])
        right_col = sorted(right_col, key=lambda b: b[1])

        #join per-column text in reading order (left first, then right)
        column_text = []
        for col in [left_col, right_col]:
            text = " ".join(b[4] for b in col)
            column_text.append(text)

        #split sentences using regex
        for text in column_text:
            
            sentences = text.replace("\n"," ") # convert newline into space
            sentences= re.sub(r'\s+', ' ', sentences) #converts multuple spaces into single space 
            sentences  = re.sub(r'[•*]','', sentences) # removes symbols • and *
            sentences = re.split(r'(?<=[.!?])\s+', sentences.strip())#seperates sentences by grammar and spaces
            all_sentences.extend(sentences)

    return all_sentences

# Example use
clean_text = extract_sentences(pdf_path)

In [16]:
clean_text[:10]

['ESG Addendum 2024 to the BT Group plc Annual Report 2024',
 '',
 'Being transparent and accountable Disclosing policies and performance Identifying our ESG priorities BT Group Manifesto – targets and progress FY23 Being transparent and accountable Disclosing policies and performance Identifying our ESG priorities BT Group Manifesto – targets and progress FY23 Our social and economic contribution Environmental management Environmental data People data Sustainability Accounting Standards Board (SASB) index Our social and economic contribution Environmental management Environmental data People data Sustainability Accounting Standards Board (SASB) index “As a responsible business, we openly and regularly share the progress we are making on the BT Group Manifesto and in support of our purpose, to connect for good.',
 'Being transparent through our ESG disclosures is essential in building trust with all of our stakeholders.',
 'It provides tangible proof of how we’re making a positive contribution to society and the environment, and helps us to grow our business, reduce risk, and attract and retain diverse talent.',
 'We report on material ESG topics in our Annual Report; this Addendum offers more detailed data and disclosures to meet growing expectations for enhanced transparency on ESG topics.',
 'Oversight of progress on the Manifesto and our ESG reporting is integrated across our governance structures.',
 'Over recent years, we’ve seen a huge shift in the ESG reporting landscape, which advance the range of disclosures that we and other businesses make.',
 'We’d like to see greater levels of consistency and further coordination among regulators and standard- setters, to enable us to provide the most meaningful, comparable and efficient response.',
 'Simon Lowth Chief Financial Officer 02 BT Group plc ESG Addendum to the BT Group plc Annual Report 2024 02 BT Group plc ESG Addendum to the BT Group plc Annual Report 2024']

In [ ]:
# 2) Transfrorm & load: Convert from PDF to list of clean sentences

# pdf_location = r'data/LSE_VTC_2023.pdf' #NYSE_MCD_2023.pdf
# def pdfparser(pdf_location):
#     def pdf_to_text(pdf_url):
#         """
#         Converts PDF into string
#         """
#         all_text = ""
#         with pdfplumber.open(f"{pdf_url}") as pdf:
#             for page in pdf.pages:
#                 text = page.extract_text()
#                 if text: 
#                     all_text += text + " "
#         return all_text.strip()

#     def get_clean_text(text):
#         """
#         Cleans input text
#         """
#         text = text.replace("\n"," ") # convert newline into space
#         text = re.sub(r'\s+', ' ', text) #convert multuple spaces into single space 
#         text = re.sub(r'[•*]','', text) # removes symbols • and *
#         return text.strip()

#     def get_clean_text_to_list(words):
#         """
#         Splits clean text from words into sentences, then returns as list
#         """
#         sentences = get_clean_text(words)
#         sentences = re.split(r'(?<=[.!?])\s+', sentences)
#         return [s.strip() for s in sentences if s.strip()]
        
#     pdf_text = pdf_to_text(pdf_location)
#     return get_clean_text_to_list(pdf_text)

# clean_text = pdfparser(pdf_location)

In [17]:
print(f"Length of company filing in sentences: {len(clean_text )}")
print(f"Sample sentences: {clean_text [:3]}")

Length of company filing in sentences: 233
Sample sentences: ['ESG Addendum 2024 to the BT Group plc Annual Report 2024', '', 'Being transparent and accountable Disclosing policies and performance Identifying our ESG priorities BT Group Manifesto – targets and progress FY23 Being transparent and accountable Disclosing policies and performance Identifying our ESG priorities BT Group Manifesto – targets and progress FY23 Our social and economic contribution Environmental management Environmental data People data Sustainability Accounting Standards Board (SASB) index Our social and economic contribution Environmental management Environmental data People data Sustainability Accounting Standards Board (SASB) index “As a responsible business, we openly and regularly share the progress we are making on the BT Group Manifesto and in support of our purpose, to connect for good.']

In [18]:
# 3) Import ESG Models, return esg classifications per sentence

### Load the models (takes ca. 1 min)
# Environmental model.
name = "ESGBERT/EnvironmentalBERT-environmental" # path to download from HuggingFace
# In simple words, the tokenizer prepares the text for the model and the model classifies the text-
tokenizer = AutoTokenizer.from_pretrained(name)
model = AutoModelForSequenceClassification.from_pretrained(name)
# The pipeline combines tokenizer and model to one process.
pipe_env = pipeline("text-classification", model=model, tokenizer=tokenizer)

# Also load the social and governance model.
# Social model.
name = "ESGBERT/SocialBERT-social"
tokenizer = AutoTokenizer.from_pretrained(name)
model = AutoModelForSequenceClassification.from_pretrained(name)
pipe_soc = pipeline("text-classification", model=model, tokenizer=tokenizer)

# Governance model.
name = "ESGBERT/GovernanceBERT-governance"
tokenizer = AutoTokenizer.from_pretrained(name)
model = AutoModelForSequenceClassification.from_pretrained(name)
pipe_gov = pipeline("text-classification", model=model, tokenizer=tokenizer)

pipe_senti = pipeline("sentiment-analysis", model="distilbert/distilbert-base-uncased-finetuned-sst-2-english", framework="pt")

Device set to use cpu
Device set to use cpu
Device set to use cpu
Device set to use cpu

In [19]:
# example outputs
test = pipe_env(clean_text[:10]) # Test for environmental classification..
test1 = pipe_soc(clean_text[:10])
test2 = pipe_gov(clean_text[:10])
test3 = pipe_senti(clean_text[:10])
print(test)
print(test1)
print(test2)
print(test3)

[{'label': 'environmental', 'score': 0.9968069791793823}, {'label': 'none', 'score': 0.5749638676643372}, {'label': 'environmental', 'score': 0.9947894811630249}, {'label': 'environmental', 'score': 0.9954741597175598}, {'label': 'environmental', 'score': 0.9947726130485535}, {'label': 'environmental', 'score': 0.9964475631713867}, {'label': 'environmental', 'score': 0.9935089349746704}, {'label': 'environmental', 'score': 0.9966629147529602}, {'label': 'none', 'score': 0.991610586643219}, {'label': 'environmental', 'score': 0.9957703948020935}]
[{'label': 'social', 'score': 0.9990873336791992}, {'label': 'none', 'score': 0.6290034651756287}, {'label': 'social', 'score': 0.9992954730987549}, {'label': 'social', 'score': 0.9995537400245667}, {'label': 'social', 'score': 0.9997678399085999}, {'label': 'social', 'score': 0.9994131326675415}, {'label': 'social', 'score': 0.9994210004806519}, {'label': 'social', 'score': 0.9994650483131409}, {'label': 'none', 'score': 0.9999068975448608}, {'label': 'social', 'score': 0.999273955821991}]
[{'label': 'governance', 'score': 0.9815770983695984}, {'label': 'none', 'score': 0.7728855609893799}, {'label': 'governance', 'score': 0.96599280834198}, {'label': 'governance', 'score': 0.991395890712738}, {'label': 'none', 'score': 0.9924535155296326}, {'label': 'governance', 'score': 0.9764452576637268}, {'label': 'governance', 'score': 0.994362473487854}, {'label': 'governance', 'score': 0.9457722306251526}, {'label': 'none', 'score': 0.8782823085784912}, {'label': 'governance', 'score': 0.8358469009399414}]
[{'label': 'NEGATIVE', 'score': 0.6513208150863647}, {'label': 'POSITIVE', 'score': 0.7481209635734558}, {'label': 'POSITIVE', 'score': 0.9937657117843628}, {'label': 'POSITIVE', 'score': 0.9991870522499084}, {'label': 'POSITIVE', 'score': 0.9998637437820435}, {'label': 'POSITIVE', 'score': 0.9492931962013245}, {'label': 'POSITIVE', 'score': 0.9982272982597351}, {'label': 'POSITIVE', 'score': 0.999358594417572}, {'label': 'POSITIVE', 'score': 0.9993873834609985}, {'label': 'NEGATIVE', 'score': 0.8085829019546509}]

In [20]:
sample_text = clean_text
ESG_features = [pipe_env, pipe_soc, pipe_gov, pipe_senti]
def text_to_scored_ESG_(ESG_features):
    """_
    Applies ESG model to text, returns df of sentence labels and scores 
    
    """
    report_df = pd.DataFrame({"sentence":sample_text})
     
    for pipe in ESG_features:

        results = pipe(sample_text, padding=True, truncation=True)

        labels = [x["label"] for x in results]
        scores = [x["score"] for x in results]


        if pipe == pipe_env:
            report_df["Environment"] = labels 
            report_df["Env_score"] = scores
            
        elif pipe == pipe_soc:
            report_df["Social"] = labels 
            report_df["Social_score"] = scores
            
        elif pipe == pipe_gov:
            report_df["Government"] = labels 
            report_df["Gov_score"] = scores
            
        else:
            report_df["Sentiment"] = labels 
            report_df["Senti_score"] = scores
            
            
    return report_df
        
df = text_to_scored_ESG_(ESG_features)
df.head(10)

,sentence,Environment,Env_score,Social,Social_score,Government,Gov_score,Sentiment,Senti_score
0,ESG Addendum 2024 to the BT Group plc Annual R...,environmental,0.996807,social,0.999087,governance,0.981577,NEGATIVE,0.651321
1,,none,0.574964,none,0.629003,none,0.772886,POSITIVE,0.748121
2,Being transparent and accountable Disclosing p...,environmental,0.994789,social,0.999295,governance,0.965993,POSITIVE,0.993766
3,Being transparent through our ESG disclosures ...,environmental,0.995474,social,0.999554,governance,0.991396,POSITIVE,0.999187
4,It provides tangible proof of how we’re making...,environmental,0.994773,social,0.999768,none,0.992454,POSITIVE,0.999864
5,We report on material ESG topics in our Annual...,environmental,0.996448,social,0.999413,governance,0.976445,POSITIVE,0.949293
6,Oversight of progress on the Manifesto and our...,environmental,0.993509,social,0.999421,governance,0.994362,POSITIVE,0.998227
7,"Over recent years, we’ve seen a huge shift in ...",environmental,0.996663,social,0.999465,governance,0.945772,POSITIVE,0.999359
8,We’d like to see greater levels of consistency...,none,0.991611,none,0.999907,none,0.878282,POSITIVE,0.999387
9,Simon Lowth Chief Financial Officer 02 BT Grou...,environmental,0.995770,social,0.999274,governance,0.835847,NEGATIVE,0.808583

In [26]:
#ESG Risk scoring:

def esg_risk_score(row):
    risk = 0
    # Environment
    if row["Environment"] != "none" and row["Sentiment"] == "NEGATIVE":
        risk += row["Env_score"] * row["Senti_score"]
    # Social
    if row["Social"] != "none" and row["Sentiment"] == "NEGATIVE":
        risk += row["Social_score"] * row["Senti_score"]
    # Governance
    if row["Government"] != "none" and row["Sentiment"] == "NEGATIVE":
        risk += row["Gov_score"] * row["Senti_score"]
    return risk

# Apply to dataframe
df["ESG_risk_score"] = df.apply(esg_risk_score, axis=1)

# Optional: total ESG risk for the whole document/report
total_esg_risk = df["ESG_risk_score"].sum()

print(df[["sentence","ESG_risk_score"]])
print("Total ESG risk:", total_esg_risk)

                                              sentence  ESG_risk_score
0    ESG Addendum 2024 to the BT Group plc Annual R...        1.939289
1                                                             0.000000
2    Being transparent and accountable Disclosing p...        0.000000
3    Being transparent through our ESG disclosures ...        0.000000
4    It provides tangible proof of how we’re making...        0.000000
..                                                 ...             ...
228  We do not currently report on the metrics defi...        0.000000
229  AR, How we manage risk, pages 68-70 94,722 Pet...        0.000000
230  © BT Group plc Registered office: 1 Braham, Br...        0.000000
231            4190816 Produced by BT Group plc bt.com        0.000000
232                                                           0.000000

[233 rows x 2 columns]
Total ESG risk: 115.48680655350569

In [27]:
df_sorted = df.sort_values(by="ESG_risk_score", ascending=False)
df_sorted

,sentence,Environment,Env_score,Social,Social_score,Government,Gov_score,Sentiment,Senti_score,ESG_risk_score
107,Being transparent and accountable Disclosing p...,environmental,0.996133,social,0.998389,governance,0.983968,NEGATIVE,0.999524,2.977073
195,Being transparent and accountable Disclosing p...,environmental,0.993466,social,0.999026,governance,0.978327,NEGATIVE,0.994012,2.953029
212,Being transparent and accountable Disclosing p...,environmental,0.991062,social,0.998013,governance,0.975006,NEGATIVE,0.992010,2.940398
164,Being transparent and accountable Disclosing p...,environmental,0.990368,social,0.999534,governance,0.981231,NEGATIVE,0.987023,2.932576
141,Being transparent and accountable Disclosing p...,environmental,0.994776,social,0.996762,governance,0.966582,NEGATIVE,0.991211,2.932122
...,...,...,...,...,...,...,...,...,...,...
87,"If any issues occur, we work with the relevant...",none,0.996041,none,0.999949,none,0.996945,POSITIVE,0.674371,0.000000
88,We aim to meet our commitments under the Envir...,environmental,0.997434,none,0.979117,none,0.997177,POSITIVE,0.977233,0.000000
89,No major environmental breaches have occurred ...,environmental,0.966035,none,0.999948,none,0.997733,POSITIVE,0.928306,0.000000
90,Managing environmental risk We take a consiste...,environmental,0.993222,social,0.999305,none,0.938541,POSITIVE,0.995037,0.000000
232,,none,0.574964,none,0.629003,none,0.772886,POSITIVE,0.748121,0.000000

In [29]:
df_sorted["sentence"][212]
# Sentiment model needs tweeks

'Being transparent and accountable Disclosing policies and performance Identifying our ESG priorities BT Group Manifesto targets and progress FY24 Our social and economic contribution Environmental management Environmental data People data Sustainability Accounting Standards Board (SASB) index Sustainability Accounting Standards Board (SASB) index continued Topic Code Accounting Metrics – description Category Unit of measure Response/comments Data/references Product End-of-Life Management TC-TL- 440a.1 1) Materials recovered through take back programmes, percentage of recovered materials that were: Quantitative Metric tonnes (t), 2) reused 3) recycled 4) landfilled Competitive Behaviour and Open Internet TC-TL- 520a.1 Total amount of monetary losses as a result of legal proceedings associated with anti- competitive behaviour regulations Quantitative Reporting currency We disclose material monetary losses associated with anti-competitive behaviour proceedings in our AR.'

In [ ]:
#Next step: store scores in db for all companies? docker postgres db??

In [ ]:
# 5) Calculate risk score and classify company: save to dataframe or database (postgres) and add fast api to look up company and return risk score and classification
#to do:
#def store_ESG_Risk_Scores():
#-Sentence/ column detection

In [ ]:
#def Run_ESG_Risk_analysis(list_of_companies):
#- normalise all company risk scores
#-  risk < 25 = low risk,
#- 25 < risk < 60 = med risk
#- 60< risk < 80 = high risk
#- 80+ = very high risk

In [ ]:
#def return_ESG_Risk_Score():
#use FastAPI to query and return scores from ESG_Risk_database

In [ ]:
# 6+) Apply MLOPS and productionarise: Containerise, orchestrate, monitor -> finetune ESG hugging face model -> Visualisations in streamlit server